# Stereo Camera paremeters
# These parameters are used for the stereo camera processing nodes

#============================================
# Rectification Parameters
#============================================
rectify_left:
  ros__parameters:
    use_sim_time: True
    approximate_sync: True
    queue_size: 50

rectify_right:
  ros__parameters:
    use_sim_time: True
    approximate_sync: True
    queue_size: 50

#============================================
# Disparity Map Parameters
#============================================
disparity_map:
  ros__parameters:
    use_sim_time: True
    approximate_sync: True
    queue_size: 50
    stereo_algorithm: 1 # 0 = BM (faster), 1 = SGBM (more accurate)
    correlation_window_size: 11
    min_disparity: 2
    num_disparities: 48 # multiple of 16

#============================================
# Stereo View Parameters
#============================================
stereo_view_node:
  ros__parameters:
    use_sim_time: True
    approximate_sync: True
    queue_size: 50 
