#!/usr/bin/env python3

import argparse
import csv
import math
import os
import sys


def _load_csv(csv_path):
    data = {
        't': [],
        'ex': [],
        'ey': [],
        'eyaw': [],
        'evx': [],
        'evy': [],
        'ewz': [],
    }

    raw_columns = [
        'ekf_x', 'ekf_y', 'ekf_yaw', 'ekf_vx', 'ekf_vy', 'ekf_wz',
        'stereo_x', 'stereo_y', 'stereo_yaw', 'stereo_vx', 'stereo_vy', 'stereo_wz',
    ]

    with open(csv_path, 'r', newline='') as f:
        reader = csv.DictReader(f)
        required = set(data.keys())
        if reader.fieldnames is None:
            raise RuntimeError('CSV header missing.')
        missing = required.difference(reader.fieldnames)
        if missing:
            raise RuntimeError(f'Missing CSV columns: {sorted(missing)}')

        has_raw_values = set(raw_columns).issubset(set(reader.fieldnames))
        if has_raw_values:
            for key in raw_columns:
                data[key] = []

        for row in reader:
            for key in data:
                data[key].append(float(row[key]))

    if not data['t']:
        raise RuntimeError('CSV is empty: no samples to plot.')

    t0 = data['t'][0]
    data['t'] = [t - t0 for t in data['t']]
    data['has_raw_values'] = has_raw_values
    return data


def _compute_mean(values):
    return sum(values) / len(values)


def _compute_rmse(values):
    return math.sqrt(sum(v * v for v in values) / len(values))


def _compute_variance(values):
    mean = _compute_mean(values)
    return max(0.0, sum((v - mean) * (v - mean) for v in values) / len(values))


def _print_error_stats(data):
    fields = ['ex', 'ey', 'eyaw', 'evx', 'evy', 'ewz']
    units = {
        'ex': 'm',
        'ey': 'm',
        'eyaw': 'rad',
        'evx': 'm/s',
        'evy': 'm/s',
        'ewz': 'rad/s',
    }

    print('Error statistics: mean, RMSE, variance, std')
    for field in fields:
        values = data[field]
        mean = _compute_mean(values)
        rmse = _compute_rmse(values)
        variance = _compute_variance(values)
        std = math.sqrt(variance)
        print(
            f'{field}: mean={mean:.6f} {units[field]}, '
            f'rmse={rmse:.6f} {units[field]}, '
            f'var={variance:.6f} {units[field]}^2, '
            f'std={std:.6f} {units[field]}'
        )


def _subset_data(data, start_idx, end_idx):
    subset = {'has_raw_values': data['has_raw_values']}
    for key, values in data.items():
        if isinstance(values, list):
            subset[key] = values[start_idx:end_idx]
    return subset


def _find_divergence_index(data, ex_thr, ey_thr, eyaw_thr_deg, min_consecutive):
    eyaw_thr_rad = math.radians(eyaw_thr_deg)
    count = 0
    start_idx = None
    for i, (ex, ey, eyaw) in enumerate(zip(data['ex'], data['ey'], data['eyaw'])):
        unstable = abs(ex) > ex_thr or abs(ey) > ey_thr or abs(eyaw) > eyaw_thr_rad
        if unstable:
            if start_idx is None:
                start_idx = i
            count += 1
            if count >= min_consecutive:
                return start_idx
        else:
            count = 0
            start_idx = None
    return None


def _build_unstable_intervals(data, ex_thr, ey_thr, eyaw_thr_deg):
    eyaw_thr_rad = math.radians(eyaw_thr_deg)
    flags = [
        abs(ex) > ex_thr or abs(ey) > ey_thr or abs(eyaw) > eyaw_thr_rad
        for ex, ey, eyaw in zip(data['ex'], data['ey'], data['eyaw'])
    ]

    intervals = []
    start = None
    for i, flag in enumerate(flags):
        if flag and start is None:
            start = i
        if not flag and start is not None:
            intervals.append((data['t'][start], data['t'][i - 1]))
            start = None
    if start is not None:
        intervals.append((data['t'][start], data['t'][-1]))
    return intervals


def _shade_intervals(axs, intervals):
    for ax in axs:
        first = True
        for t0, t1 in intervals:
            label = 'unstable interval' if first else None
            ax.axvspan(t0, t1, color='red', alpha=0.08, label=label)
            first = False


def main():
    parser = argparse.ArgumentParser(
        description='Plot EKF-vs-stereo odometry errors from odom_comparator CSV output.'
    )
    parser.add_argument(
        '--csv',
        default='/tmp/odom_comparison.csv',
        help='Path to CSV generated by odom_comparator.py',
    )
    parser.add_argument(
        '--save',
        default='',
        help='Optional output image path (e.g., /tmp/odom_plot.png).',
    )
    parser.add_argument(
        '--no-show',
        action='store_true',
        help='Do not open an interactive window.',
    )
    parser.add_argument('--ex-threshold', type=float, default=0.10, help='Unstable threshold for |ex| [m].')
    parser.add_argument('--ey-threshold', type=float, default=0.10, help='Unstable threshold for |ey| [m].')
    parser.add_argument('--eyaw-threshold-deg', type=float, default=15.0, help='Unstable threshold for |eyaw| [deg].')
    parser.add_argument('--min-consecutive', type=int, default=20, help='Consecutive unstable samples to mark divergence start.')
    args = parser.parse_args()

    if not os.path.exists(args.csv):
        print(f'CSV not found: {args.csv}', file=sys.stderr)
        sys.exit(1)

    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print('matplotlib is required. Install with: sudo apt install python3-matplotlib', file=sys.stderr)
        sys.exit(2)

    try:
        data = _load_csv(args.csv)
    except Exception as exc:
        print(f'Failed to load CSV: {exc}', file=sys.stderr)
        sys.exit(3)

    if data['has_raw_values']:
        print('Raw EKF/stereo columns detected: plotting raw values and errors.')
    else:
        print('Raw EKF/stereo columns not found: plotting error-only view (legacy CSV).')

    _print_error_stats(data)

    divergence_idx = _find_divergence_index(
        data,
        ex_thr=args.ex_threshold,
        ey_thr=args.ey_threshold,
        eyaw_thr_deg=args.eyaw_threshold_deg,
        min_consecutive=max(1, args.min_consecutive),
    )
    unstable_intervals = _build_unstable_intervals(
        data,
        ex_thr=args.ex_threshold,
        ey_thr=args.ey_threshold,
        eyaw_thr_deg=args.eyaw_threshold_deg,
    )

    if divergence_idx is not None:
        t_div = data['t'][divergence_idx]
        print(
            f'Estimated divergence start: t={t_div:.3f}s '
            f'(thresholds: |ex|>{args.ex_threshold}m, |ey|>{args.ey_threshold}m, '
            f'|eyaw|>{args.eyaw_threshold_deg}deg, min_consecutive={args.min_consecutive})'
        )
        pre = _subset_data(data, 0, divergence_idx)
        post = _subset_data(data, divergence_idx, len(data['t']))
        if len(pre['t']) >= 5:
            print('Pre-divergence stats:')
            _print_error_stats(pre)
        if len(post['t']) >= 5:
            print('Post-divergence stats:')
            _print_error_stats(post)
    else:
        print('No divergence interval detected with the current thresholds.')

    rmse_x = _compute_rmse(data['ex'])
    rmse_y = _compute_rmse(data['ey'])
    rmse_yaw_deg = math.degrees(_compute_rmse(data['eyaw']))
    rmse_vx = _compute_rmse(data['evx'])
    rmse_vy = _compute_rmse(data['evy'])
    rmse_wz = _compute_rmse(data['ewz'])

    std_x = math.sqrt(_compute_variance(data['ex']))
    std_y = math.sqrt(_compute_variance(data['ey']))
    std_yaw_deg = math.degrees(math.sqrt(_compute_variance(data['eyaw'])))
    std_vx = math.sqrt(_compute_variance(data['evx']))
    std_vy = math.sqrt(_compute_variance(data['evy']))
    std_wz = math.sqrt(_compute_variance(data['ewz']))

    rows = 6 if data['has_raw_values'] else 3
    fig, axs = plt.subplots(rows, 1, figsize=(11, 3 * rows), sharex=True)
    axs = list(axs)

    idx = 0
    if data['has_raw_values']:
        axs[idx].plot(data['t'], data['ekf_x'], label='ekf_x', linewidth=1.1)
        axs[idx].plot(data['t'], data['stereo_x'], label='stereo_x', linewidth=1.1)
        axs[idx].plot(data['t'], data['ekf_y'], label='ekf_y', linewidth=1.1)
        axs[idx].plot(data['t'], data['stereo_y'], label='stereo_y', linewidth=1.1)
        axs[idx].set_ylabel('position [m]')
        axs[idx].grid(True, alpha=0.3)
        axs[idx].legend(loc='upper right', ncol=2)
        idx += 1

        ekf_yaw_deg = [math.degrees(v) for v in data['ekf_yaw']]
        stereo_yaw_deg = [math.degrees(v) for v in data['stereo_yaw']]
        axs[idx].plot(data['t'], ekf_yaw_deg, label='ekf_yaw', linewidth=1.1)
        axs[idx].plot(data['t'], stereo_yaw_deg, label='stereo_yaw', linewidth=1.1)
        axs[idx].set_ylabel('yaw [deg]')
        axs[idx].grid(True, alpha=0.3)
        axs[idx].legend(loc='upper right')
        idx += 1

        axs[idx].plot(data['t'], data['ekf_vx'], label='ekf_vx', linewidth=1.1)
        axs[idx].plot(data['t'], data['stereo_vx'], label='stereo_vx', linewidth=1.1)
        axs[idx].plot(data['t'], data['ekf_vy'], label='ekf_vy', linewidth=1.1)
        axs[idx].plot(data['t'], data['stereo_vy'], label='stereo_vy', linewidth=1.1)
        axs[idx].plot(data['t'], data['ekf_wz'], label='ekf_wz', linewidth=1.1)
        axs[idx].plot(data['t'], data['stereo_wz'], label='stereo_wz', linewidth=1.1)
        axs[idx].set_ylabel('raw velocity')
        axs[idx].grid(True, alpha=0.3)
        axs[idx].legend(loc='upper right', ncol=2)
        idx += 1

    axs[idx].plot(
        data['t'],
        data['ex'],
        label=f'ex (RMSE={rmse_x:.3f} m, STD={std_x:.3f} m)',
        linewidth=1.2,
    )
    axs[idx].plot(
        data['t'],
        data['ey'],
        label=f'ey (RMSE={rmse_y:.3f} m, STD={std_y:.3f} m)',
        linewidth=1.2,
    )
    axs[idx].set_ylabel('position error [m]')
    axs[idx].grid(True, alpha=0.3)
    axs[idx].legend(loc='upper right')
    idx += 1

    eyaw_deg = [math.degrees(v) for v in data['eyaw']]
    axs[idx].plot(
        data['t'],
        eyaw_deg,
        label=f'eyaw (RMSE={rmse_yaw_deg:.2f} deg, STD={std_yaw_deg:.2f} deg)',
        linewidth=1.2,
    )
    axs[idx].set_ylabel('yaw error [deg]')
    axs[idx].grid(True, alpha=0.3)
    axs[idx].legend(loc='upper right')
    idx += 1

    axs[idx].plot(
        data['t'],
        data['evx'],
        label=f'evx (RMSE={rmse_vx:.3f} m/s, STD={std_vx:.3f} m/s)',
        linewidth=1.2,
    )
    axs[idx].plot(
        data['t'],
        data['evy'],
        label=f'evy (RMSE={rmse_vy:.3f} m/s, STD={std_vy:.3f} m/s)',
        linewidth=1.2,
    )
    axs[idx].plot(
        data['t'],
        data['ewz'],
        label=f'ewz (RMSE={rmse_wz:.3f} rad/s, STD={std_wz:.3f} rad/s)',
        linewidth=1.2,
    )
    axs[idx].set_ylabel('velocity error')
    axs[idx].set_xlabel('time from start [s]')
    axs[idx].grid(True, alpha=0.3)
    axs[idx].legend(loc='upper right')

    if unstable_intervals:
        _shade_intervals(axs, unstable_intervals)
        axs[0].legend(loc='upper right', ncol=2)

    fig.suptitle('EKF vs Stereo Odometry: Raw Signals and Errors')
    fig.tight_layout()

    if args.save:
        fig.savefig(args.save, dpi=160)
        print(f'Plot saved to: {args.save}')

    if not args.no_show:
        plt.show()


if __name__ == '__main__':
    main()
